requestwatch.blocking.delay-millis=150
requestwatch.allocation.buffers=768
requestwatch.allocation.buffer-size-bytes=8192
requestwatch.startup.enabled=true
requestwatch.startup.delay-millis=400
requestwatch.startup.buffers=256
requestwatch.startup.buffer-size-bytes=16384

quarkus.container-image.group=requestwatch
quarkus.container-image.name=requestwatch-jfr
quarkus.container-image.tag=1.0.0
