quarkus.datasource.db-kind=postgresql

quarkus.qubit.scanning.include-packages=com.themainthread.releaseradar.
quarkus.qubit.fail-on-analysis-error=true
quarkus.qubit.logging.log-generated-classes=true

%dev.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
%dev.quarkus.hibernate-orm.sql-load-script=import.sql
%dev.quarkus.hibernate-orm.log.sql=true
%dev.quarkus.log.category."io.quarkiverse.qubit".level=DEBUG

%test.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
%test.quarkus.hibernate-orm.sql-load-script=import.sql

%prod.quarkus.hibernate-orm.schema-management.strategy=validate
