quarkus.application.name=the-main-thread

quarkus.banner-generator.text={#3A338F}THE\n{#CC2266}MAIN {#3A338F}THREAD
quarkus.banner-generator.font=slant
quarkus.banner-generator.background-color=black
quarkus.banner-generator.alignment=center
quarkus.banner-generator.line-spacing=1

%dev.quarkus.console.basic=true
