quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.schema-management.strategy=validate
quarkus.flyway.migrate-at-start=true

%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:planner;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
%test.quarkus.datasource.devservices.enabled=false
%test.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
%test.quarkus.flyway.migrate-at-start=false
