quarkus.http.port=8080
quarkus.http.test-port=8081

quarkus.rest-client.inventory.url=http://127.0.0.1:${quarkus.http.port}
%test.quarkus.rest-client.inventory.url=http://127.0.0.1:${quarkus.http.test-port}

%dev.quarkus.goblin.enabled=true
%dev.quarkus.goblin.assault.type=LATENCY
%dev.quarkus.goblin.assault.latency.min-milliseconds=1200
%dev.quarkus.goblin.assault.latency.max-milliseconds=1500
%dev.quarkus.goblin.target.level=100
%dev.quarkus.goblin.target.include-packages=com.themainthread.goblin.inventory

%test.quarkus.goblin.enabled=true
%test.quarkus.goblin.assault.type=HTTP_STATUS
%test.quarkus.goblin.assault.http-status.code=503
%test.quarkus.goblin.assault.http-status.message=Inventory unavailable (Goblin test)
%test.quarkus.goblin.target.level=100
%test.quarkus.goblin.target.include-packages=com.themainthread.goblin.inventory
