quarkus.http.port=8081

quarkus.oidc.application-type=service
quarkus.oidc.auth-server-url=${KEYCLOAK_URL:http://localhost:8180}/realms/delegation
quarkus.oidc.client-id=service-a
quarkus.oidc.token.audience=service-a

quarkus.oidc-client.auth-server-url=${KEYCLOAK_URL:http://localhost:8180}/realms/delegation
quarkus.oidc-client.client-id=service-a
quarkus.oidc-client.credentials.secret=${SERVICE_A_SECRET}
quarkus.oidc-client.grant.type=exchange
quarkus.oidc-client.grant-options.exchange.audience=service-b
quarkus.oidc-client.grant-options.exchange.subject_token_type=urn:ietf:params:oauth:token-type:access_token
quarkus.oidc-client.grant-options.exchange.requested_token_type=urn:ietf:params:oauth:token-type:access_token
quarkus.oidc-client.connection-timeout=3S
quarkus.oidc-client.connection-retry-count=1

quarkus.rest-client-oidc-token-propagation.exchange-token=true

quarkus.rest-client.inventory.url=${INVENTORY_URL:http://localhost:8082}
quarkus.rest-client.inventory.connect-timeout=3000
quarkus.rest-client.inventory.read-timeout=5000
