quarkus.http.port=8088

quarkus.flags.openfeature.pricing-engine.type=string
quarkus.flags.openfeature.pricing-engine.default-value=stable

pricing.flagd.enabled=true
pricing.flagd.host=localhost
pricing.flagd.port=8013

%test.pricing.flagd.enabled=false
