[allowlist]
  description = "Global Allowlist"

  # Ignore based on any subset of the file path
  paths = [
    # Ignore all example certs
    '''(?:^|\/)jwt-case.*\.pem$''',
    '''(?:^|\/)stateless-api.*\.pem$''',
    '''(?:^|\/)granular-rbac-tutorial.*\.pem$''',
    '''(?:^|\/)bsky-javafeed-generator2.*\.crt$''',
    '''(?:^|\/)bsky-javafeed-generator2.*\.key$''',
    '''(?:^|\/)enterprise-rag-secure\/.*\.pem$''',
    '''(?:^|\/)enterprise-rag-metadata\/.*\.pem$''',
    '''(?:^|\/)book-catalog\/.*\.pem$''',
    '''(?:^|\/)dpop-demo\/.*\.pem$''',
    '''(?:^|\/)magic-link-demo\/.*\.pem$''',
    '''(?:^|/)src/main/resources/certs/.*''',
    '''(?:^|/)src/main/resources/META-INF/resources/.*''',
    '''(?:^|/)quarkus-multi-tenant-extension\/.*\.pem$'''
    ]
