quarkus.application.name=swiftship-tracking

quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.min-size=2
quarkus.datasource.jdbc.max-size=12
quarkus.datasource.jdbc.acquisition-timeout=3s

%dev,test.quarkus.datasource.devservices.image-name=docker.io/library/postgres:18.4-alpine3.24
%dev,test.quarkus.datasource.devservices.db-name=swiftship
%dev,test.quarkus.datasource.devservices.username=swiftship
%dev,test.quarkus.datasource.devservices.password=swiftship

quarkus.flyway.migrate-at-start=true
quarkus.hibernate-orm.schema-management.strategy=validate
quarkus.hibernate-orm.log.sql=false

quarkus.container-image.group=themainthread
quarkus.container-image.name=swiftship-tracking
quarkus.container-image.labels."org.opencontainers.image.source"=https://github.com/myfear/the-main-thread/swiftship-tracking
quarkus.container-image.labels."org.opencontainers.image.title"=SwiftShip Tracking
