flamme.nats.url=${NATS_URL:nats://localhost:4222}
flamme.nats.connection-name=release-gate
flamme.reply-timeout=3

release-gate.node-id=${RELEASE_GATE_NODE_ID:monolith}

quarkus.grpc.server.use-separate-server=false
quarkus.otel.sdk.disabled=true
