quarkus.application.name=hardened-quarkus-jib

quarkus.container-image.group=themainthread
quarkus.container-image.name=hardened-quarkus-jib
quarkus.container-image.registry=localhost
quarkus.container-image.labels."org.opencontainers.image.source"=https://github.com/myfear/the-main-thread/hardened-quarkus-jib
quarkus.container-image.labels."org.opencontainers.image.title"=Hardened Quarkus with Jib

quarkus.jib.base-jvm-image=registry.access.redhat.com/hi/openjdk:25-runtime
quarkus.jib.docker-executable-name=podman
quarkus.jib.jvm-additional-arguments=-XX:MaxRAMPercentage=70.0,-XX:+ExitOnOutOfMemoryError
quarkus.jib.user=65532
quarkus.jib.working-directory=/work
quarkus.jib.use-current-timestamp=false
quarkus.jib.use-current-timestamp-file-modification=false
