quarkus.http.port=8083

quarkus.oidc.application-type=service
quarkus.oidc.auth-server-url=${KEYCLOAK_URL:http://localhost:8180}/realms/delegation
quarkus.oidc.client-id=service-c
quarkus.oidc.token.audience=service-c
