quarkus.langchain4j.ollama.base-url=http://localhost:11434
quarkus.langchain4j.ollama.timeout=240s
quarkus.langchain4j.ollama.devservices.enabled=false
quarkus.langchain4j.devservices.enabled=false

quarkus.langchain4j.granite.chat-model.provider=ollama
quarkus.langchain4j.ollama.granite.chat-model.model-id=granite4:3b
quarkus.langchain4j.ollama.granite.chat-model.temperature=0.0
quarkus.langchain4j.ollama.granite.timeout=120s

quarkus.langchain4j.mistral.chat-model.provider=ollama
quarkus.langchain4j.ollama.mistral.chat-model.model-id=mistral
quarkus.langchain4j.ollama.mistral.chat-model.temperature=0.0
quarkus.langchain4j.ollama.mistral.timeout=120s

quarkus.langchain4j.judge.chat-model.provider=ollama
quarkus.langchain4j.ollama.judge.chat-model.model-id=qwen3:4b
quarkus.langchain4j.ollama.judge.chat-model.temperature=0.0
quarkus.langchain4j.ollama.judge.timeout=120s
