quarkus.hibernate-orm.datasource=__bootstrap
quarkus.hibernate-orm.schema-management.strategy=none
quarkus.hibernate-orm.multitenant=DATABASE
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.validate-in-dev-mode=false

quarkus.datasource.devservices.enabled=false
quarkus.datasource.__bootstrap.db-kind=postgresql
quarkus.datasource.__bootstrap.devservices.db-name=bootstrap

quarkus.datasource.acme.db-kind=postgresql
quarkus.datasource.acme.devservices.db-name=acme

quarkus.datasource.globex.db-kind=postgresql
quarkus.datasource.globex.devservices.db-name=globex

quarkus.flyway.acme.locations=classpath:db/migration
quarkus.flyway.acme.migrate-at-start=true
quarkus.flyway.globex.locations=classpath:db/migration
quarkus.flyway.globex.migrate-at-start=true

quarkus.multi-tenant.http.enabled=true
quarkus.multi-tenant.http.strategy=header
quarkus.multi-tenant.http.header-name=X-Tenant
