quarkus.funqy.knative-events.mapping.scoreAlert.trigger=ingestAlert.output
quarkus.funqy.knative-events.mapping.scoreAlert.response-type=com.mainthread.alert.scored
quarkus.funqy.knative-events.mapping.scoreAlert.response-source=scoreAlert
quarkus.log.category."com.mainthread.funqyalert".level=INFO
