quarkus.http.port=8080

quarkus.stork.catalog-service.service-discovery.type=consul
quarkus.stork.catalog-service.service-discovery.consul-host=localhost
quarkus.stork.catalog-service.service-discovery.consul-port=8500
quarkus.stork.catalog-service.service-discovery.refresh-period=2S
quarkus.stork.catalog-service.load-balancer.type=round-robin
