quarkus.datasource.db-kind=postgresql

%dev.quarkus.datasource.devservices.image-name=docker.io/library/postgres:17
%test.quarkus.datasource.devservices.image-name=docker.io/library/postgres:17

%dev.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
%test.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
%prod.quarkus.hibernate-orm.schema-management.strategy=validate

%prod.quarkus.datasource.username=${DB_USERNAME}
%prod.quarkus.datasource.password=${DB_PASSWORD}
%prod.quarkus.datasource.jdbc.url=${DB_JDBC_URL}

quarkus.hibernate-orm.log.sql=false
