quarkus.http-problem.constraint-violation.status=422
quarkus.http-problem.constraint-violation.title=Validation failed
quarkus.http-problem.include-details=false

quarkus.http-problem.logging.level.4xx=INFO
quarkus.http-problem.logging.level.5xx=ERROR
quarkus.http-problem.logging.include-stack-trace=5xx
