quarkus.rest-client.nasa.url=https://exoplanetarchive.ipac.caltech.edu
quarkus.rest-client.nasa.connect-timeout=5000
quarkus.rest-client.nasa.read-timeout=60000
quarkus.cache.caffeine.catalogue.maximum-size=2
quarkus.cache.caffeine.catalogue.expire-after-write=1h
