fernbank.runtime-environment=prod
%dev.fernbank.runtime-environment=dev
%test.fernbank.runtime-environment=prod

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:6274

%dev.quarkus.mcp.server.traffic-logging.enabled=true
%dev.quarkus.mcp.server.traffic-logging.text-limit=1000
